In [ ]:
# NumPy 

In [1]:
import numpy as np

In [88]:
# NumPy Arrays
  # Creating Arrays
  # From List
arr = np.array([1,2,3,4,5])
print('array created: ', arr, type(arr))

# Multi-dimensional -:
mat = np.array([[1,2], [3,4]])
print('multi-dimentional array is: ', mat, type(mat))

# from range -:
a = np.arange(0,10,2) # (start, stop, step)
print('range of even number of array: ', a, type(a))

b = np.arange(1,11)
print('range is: ', b, type(b))

# Zeros / Ones
c = np.zeros((2,3))
print('zeros are: ', c, type(c))
d = np.ones((3,3))
print('ones are: ', d, type(d))

# Identity Matrix -:
e = np.eye(3)
print('Identity Matrix: ', e)

# Linespace -:
f = np.linspace(0,2,5) # (start, stop, difference)
print(f)

print("-"*50)
print("-"*50)
print("-"*50)

# Array Attributes -:
print('dimensions: ', arr.shape)  # dimensions
print('number of dimensions: ', arr.ndim)   # number of dimensions
print('total elements: ', arr.size)   # total elements
print('data type: ', arr.dtype)  # data type
print('bytes per element: ', arr.itemsize) # bytes per element

print("-"*50)
print("-"*50)
print("-"*50)

# Data Types -:
aa = np.array([1,2], dtype = np.float32)
print('creating array in float type: ', aa)

bb = np.array([1,2], dtype = np.complex_)
print('creating array in complet type: ', bb)

cc = np.array([1,2], dtype = np.string_)
print('creating array in string type: ', cc)

print("-"*50)
print("-"*50)
print("-"*50)

# Indexing and Slicing -:
dd = np.array([[1,2,3], [4,5,6]]) # create 2D array.
print('creating 2D array: ', dd) 
print('indexing: ', dd[0,1]) # element at row 0 & col 1.
print('slicing: ', dd[:,1])   # all rows, col 1
print('slicing: ', dd[0:2, 1:3]) # subarray
print("-"*50)
print('negative indexing: ',dd[-1]) # Negative indexing -> Last row
print('negative indexing: ', dd[:,-1]) # Negative indexing -> last col.

print("-"*50)
print("-"*50)

# Boolean Indexing -:
ee = np.array([1,2,3,4,5])
print("1D array: ", ee)
print('condition: ', ee[ee>2])

print("-"*50)
print("-"*50)

# Fancy Indexing -:
ff = np.array([10,20,30,40,50])
print('1-D array: ', ff)
print('Fancy Indexing: ', ff[[0,3]])
print('Fancy Indexing: ', ff[[0,4]])
print('Fancy Indexing: ', ff[[2,4]])

print("-"*50)
print("-"*50)

# Array Operations -:
# Element-wise:
a1 = np.array([1,2,3])
print('1D array: ', a1)
a2 = np.array([[1,2,3], [4,5,6]])
print('2D array: ', a2)
print('Add Operation: ', a1 + a2)
print('Subtract Operation: ', a2 - a1)
print('Multiplication Operation: ', a1 * a2)
print('Division Operation: ', a2 / a1)
print('Power of array: ', a1**2)

print("-"*50)
print("-"*50)

# Universal Function -:
print(a1)
print('Square root of array: ', np.sqrt(a1))
print('Expression of array: ', np.exp(a1))
print('Sin value of array: ', np.sin(a1))


print("-"*50)
print("-"*50)

# Aggregations -:
print('array is: ', a1)
print('sum is: ', a1.sum())
print('mean of array a1: ', a1.mean())
print('minimum value of array a1 is: ', a1.min())
print('maximum value of array a1 is: ', a1.max())
print('standard deviation of array a1 is: ', a1.std())
print('median value of array a1 is: ', np.median(a1))

print("-"*50)
print("-"*50)

# Broadcasting -: Rules allow operations between arrays of different shape.
a = np.array([[1], [2], [3]]) # array shape (3,1)
print(f'array is: {a}, shape is: {a.shape}')
b = np.array([4,5,6]) # array shape (3,)
print(f'array is: {b}, shape is: {b.shape}')
c = a+b
print("adding 'a' & 'b': ", c, 'and shape is: ', c.shape)


print("-"*50)
print("-"*50)

# Reshaping -:
cc = np.array([[1,2,3], [4,5,6]])
print('array is: ', cc)
print(f'Before reshaping shape of cc is: {cc.shape}, After reshaping shape of cc is: {cc.reshape(3,2)}')
print(f'{cc.ravel()}')
print(f'Before Transpose: {cc}, After Transpose: {cc.T}')

print("-"*50)

d1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(d1)
print(d1.shape)
print(d1.ravel())
d2 = d1.ravel()
print(d2[::-1])


print("-"*50)
print("-"*50)

# Stacking -:

aa1 = np.array([[1], [2], [3]])
bb1 = np.array([4,5,6])

# print(np.hstack((aa1, bb1)))
# print(np.vstack((aa1, bb1)))
# print(np.column_stack((aa1, bb1)))


print("-"*50)
print("-"*50)

# Splitting
print(arr)
# print(np.hsplit(arr,2))
# print(np.vsplit(arr, 3))

# Sorting
print(np.sort(arr))
print(arr.sort(axis=0))

b = a.view()   
print(b)
c = a.copy()
print(c)

# Random module
print('uniform [0,1]: ', np.random.rand(3, 3))        # uniform [0, 1)
print('normal dist', np.random.randn(3, 3))       # normal dist.
print(np.random.randint(1, 10, 5)) # ints
print(np.random.seed(42)) 


array created:  [1 2 3 4 5] <class 'numpy.ndarray'>
multi-dimentional array is:  [[1 2]
 [3 4]] <class 'numpy.ndarray'>
range of even number of array:  [0 2 4 6 8] <class 'numpy.ndarray'>
range is:  [ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>
zeros are:  [[0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'>
ones are:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] <class 'numpy.ndarray'>
Identity Matrix:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.  0.5 1.  1.5 2. ]
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
dimensions:  (5,)
number of dimensions:  1
total elements:  5
data type:  int32
bytes per element:  4
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
creating array in float type:  [1. 2.]
creating array in complet type:  [1.+0.j 2.+0.j]
creating array in string type:  [b'1' b

In [89]:
print(np.nan)

nan


In [90]:
np.isnan(arr)

array([False, False, False, False, False])

In [92]:
np.nan_to_num(arr)

array([1, 2, 3, 4, 5])

In [93]:
arr.size

5

In [94]:
print("-"*50)
print("-"*50)
print("-"*50)
print("-"*50)
print("-"*50)
print("-"*50)

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------


In [95]:
#######################################################################################################
#######################################################################################################

In [ ]:
# PANDAS -: (Python Data Analysis Library)
          # Pandas is built on top of NumPy and is the go-to tool for:
